server:
  port: 9930


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.123.100:3306/ebank-fast?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: '!5OMG7eW'
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.cloudplus.oauth.yinyinoauth.project.**.domain

logging:
  level:
    org.springframework: debug

#security:
#  oauth2:
#    client:
#      client-id: yinyinShop
#      client-secret: 123456
#      access-token-uri: http://localhost:9930/oauth/token
#      user-authorization-uri: http://localhost:9930/oauth/authorize
#    resource:
#      id: resource
#      token-info-uri: http://localhost:9930/oauth/check_token